# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='username',
            field=models.CharField(default='aaa', max_length=10),
            preserve_default=False,
        ),
    ]
